name: XOXO_Battle
description: "A new Flutter project for multiplayer game."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # Audio PLayer
  audioplayers: ^6.1.0
  # Confetti Effect
  confetti: ^0.8.0
  # For Local Data
  shared_preferences: ^2.3.3
  # For Show Case View
  showcaseview: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For Linting
  flutter_lints: ^5.0.0
  # For Launcher Icon
  flutter_launcher_icons: ^0.14.0

flutter_icons:  
  android: true  
  ios: false
  image_path: "assets/images/app_logo.png"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  adaptive_icon_background: "#5F8F3C"
  remove_alpha_ios: true
  min_sdk_android: 21



# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/audios/
    - assets/images/

  fonts:
    - family: Coiny
      fonts:
        - asset: assets/fonts/Coiny-Regular.ttf